# Generated by Django 2.1.7 on 2022-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('limit_temperature', models.FloatField()),
                ('limit_humidity', models.FloatField()),
            ],
            options={
                'db_table': 'commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('transportation_time', models.FloatField()),
                ('check_temperature', models.SmallIntegerField()),
                ('check_humidity', models.SmallIntegerField()),
                ('phone_number', models.IntegerField()),
                ('check_complete', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'order_main',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('realtime', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('probability_temperature', models.FloatField(blank=True, null=True)),
                ('probability_humidity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('start_place', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_key', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('identify', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
